# docker-compose.yml
version: '3.9'

services:
  db:
    image: postgres:15
    container_name: hono_postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: hono_postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
